apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: projbackend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projbackend
  template:
    metadata:
      labels:
        app: projbackend
    spec:
      containers:
      - name: projbackend
        image: abdulbarakeh/projbackend
        ports:
        - containerPort: 80