apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: projbackend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000

      Husk at lave den om til intern service 